### PR TITLE
WW/CW LED Controller

### PR DESCRIPTION
**Pull request by bassiebulk**
Added this one:
https://www.aliexpress.com/store/product/GLEDOPTO-ZIGBEE-bridge-Led-Controller-ww-cw-dimmer-strip-Controller-DC12-24V-zll-standard-led/3685003_32856512646.html?spm=2114.12010608.0.0.610464c4dzKhdx

### CODE REVIEW

**Comment by mruiter** [comment]
Thx !!!

**Comment by motor4all** [comment]
Also tested with the dimmer only (256).
You combined it with the RGB in the code, but when using the dimmer, the other settings don't make sense since you can only dimm the strip.

Op 18 okt. 2018, om 11:43 heeft Marco Ruiter <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


Thx !!!

**Comment by mruiter** [comment]
A user reported 256 as also being a rgb strip . What device is the 256 at you’re device . Maybee it was a firmware glitch at the other user

Verstuurd vanaf mijn iPhone

**Comment by motor4all** [comment]
256 is the Wireless Led Dimmer in my case!

Franz

Op 19 okt. 2018, om 21:00 heeft Marco Ruiter <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:

A user reported 256 as also being a rgb strip . What device is the 256 at you’re device . Maybee it was a firmware glitch at the other user

Verstuurd vanaf mijn iPhone

**Pull request merged**
